// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    ISymbol: typeof import('./src/components/ISymbol.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
